[package]
name = "maildir_ai"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
getopts = "0.2.21"
tokio = "1.40.0"

arrrg = "0.5"
arrrg_derive = "0.5"
utf8path = "0.6"
yammer = "0.5"
